#!/bin/bash

RED="\e[41m\e[30m"
GREEN="\e[32m"
RESET="\e[0m"
YELLOW="\e[1m\e[1;33m"

total=0
fail=0
for file in test/*.sh; do
        printf "%s\n" "=== RUNNING TEST $file ==="
        ./$file
        [ $? -eq 0 ] || let fail++
        let total++
        printf "\n%s\n" "################################################################################"
done
if [[ $fail -gt 0 ]]; then
        echo -e "$RED TESTS COMPLETED WITH ERRORS: $fail/$total failed.$RESET"
        exit -1;
else 
        echo -e "$GREEN $total/$total TESTS COMPLETED SUCCESSFULLY$RESET"
        exit 0;
fi
