name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Updating package repository
      run: sudo apt update && sudo apt -y upgrade

    - name: Installing OpenSSL
      run: sudo apt -y install openssl
    
    - name: Installing curl
      run: sudo apt -y install libcurl4-openssl-dev
      
    - name: Installing cJSON
      run: sudo apt -y install libcjson-dev

    - name: Installing Pebble
      run: sudo apt -y install pebble

    - name: Setting up static DNS entries
      run: echo -e "127.0.0.1 pebble\n \
                    ::1       pebble\n \
                    127.0.0.1 example.com\n \
                    ::1       example.com" | sudo tee /etc/hosts
    - name: Restart DNS server
      run: sudo systemctl restart systemd-resolved

    - name: Test DNS server
      run: dig example.com

    - name: Build
      run: cmake -DBUILD_TESTS=1 -B build && cd build && make

    - name: Test
      run: cd build && ctest --rerun-failed --output-on-failure
      
