name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Updating package repository
      run: sudo apt update && sudo apt -y upgrade

    - name: Installing OpenSSL
      run: sudo apt -y install openssl
    
    - name: Installing curl
      run: sudo apt -y install libcurl4-openssl-dev
      
    - name: Installing cJSON
      run: sudo apt -y install libcjson-dev

    - name: Installing Pebble
      run: sudo apt -y install pebble

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      # Build your program with the given configuration
      run: cmake -DBUILD_TESTS && make

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: make test
      
