name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Updating package repository
      run: sudo apt update && sudo apt -y upgrade

    - name: Installing necessary packages 
      run: sudo apt -y install openssl libcurl4-openssl-dev libcjson-dev pebble valgrind
   
      # To test domain validation, the domains must be resolved to localhost
      # so they point to the pebble testing server
    - name: Setting up static DNS entries
      run:  sudo cp test/hosts /etc/hosts && cat /etc/hosts
    
    - name: Restart DNS server
      run: sudo systemctl restart systemd-resolved

    - name: Test DNS server
      run: dig example.com && dig foobar.domain.com

    - name: Build
      run: cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -B build && cd build && make

    - name: Test
      run: cd build && ctest --rerun-failed --output-on-failure
     
    - name: Coverage
      run: sudo apt -y install lcov &&
           cd build && gcov src/CMakeFiles/acme-client.dir/* &&
           lcov --capture --directory . --output-file out.info-file &&
           genhtml out.info-file &&
           curl -Os https://uploader.codecov.io/latest/linux/codecov &&
           chmod +x codecov &&
           ./codecov
    - uses: actions/upload-artifact@v3
      with:
        name: testing-log
        path: build/Testing/Temporary/LastTest.log
        if-no-files-found: error

